#!/usr/bin/env python3

import cairo
from sys import argv, exit
from math import pi

from visual_puzzle import VisualPuzzle
from style import Style

def initialize_data_structure (size):
    data = []
    for y in range(size):
        row = []
        for x in range(size):
            row.append(set())
        data.append(row)
    return data

class RCVisualPuzzle (VisualPuzzle):
    
    def _pre_render (self, style, context):
        print('inside')
        data = self.data
        line_width = style.compliance_line_width
        radius     = style.compliance_radius
        border     = style.border
        height     = style.height
        width      = style.width
        
        cellheight = (height-2*border)/self.size
        cellwidth  = (width-2*border)/self.size
        
        # initialize data structure
        rrows  = initialize_data_structure(self.size)
        rcols  = initialize_data_structure(self.size)
        rcells = initialize_data_structure(self.size)
        
        # fill out data structure
        for v in range(1,self.size+1):
            for major in range(self.size):
                found_rows  = False
                found_cols  = False
                found_cells = False
                print('a v=%d major=%d found_(rows|cols|cells)=(%r|%r|%r)' % (v, major, found_rows, found_cols, found_cells))
                for minor in range(self.size):
                    if data[major][minor]==v: found_rows = True
                    if data[minor][major]==v: found_cols = True
                    if data[self.base*(major//self.base)+minor//self.base][self.base*(major%self.base)+minor%self.base]==v: found_cells = True
                print('b v=%d major=%d found_(rows|cols|cells)=(%r|%r|%r)' % (v, major, found_rows, found_cols, found_cells))
                
                if not found_rows:
                    for minor in range(self.size):
                        if data[major][minor]==-1:
                            rrows[major][minor].add(v)
                print('c v=%d major=%d found_(rows|cols|cells)=(%r|%r|%r)' % (v, major, found_rows, found_cols, found_cells))
                if not found_cols:
                    for minor in range(self.size):
                        if data[minor][major]==-1:
                            rcols[minor][major].add(v)
                print('d v=%d major=%d found_(rows|cols|cells)=(%r|%r|%r)' % (v, major, found_rows, found_cols, found_cells))
                if not found_cells:
                    for minor in range(self.size):
                        if data[self.base*(major//self.base)+minor//self.base][self.base*(major%self.base)+minor%self.base]==-1:
                            rcells[self.base*(major//self.base)+minor//self.base][self.base*(major%self.base)+minor%self.base].add(v)
                print('e v=%d major=%d found_(rows|cols|cells)=(%r|%r|%r)' % (v, major, found_rows, found_cols, found_cells))
        
        # render data structure: rows
        for r in range(len(rrows)):
            row = rrows[r]
            for c in range(len(row)):
                cell = row[c]
                for v in cell:
                    y = border + cellheight*r + border+(cellheight-2*border)/(self.size-1)*(v-1)
                    x1 = border + cellwidth*c + border
                    x2 = border + cellwidth*c + cellwidth - border
                    
                    context.save()
                    context.move_to(x1, y)
                    context.line_to(x2, y)
                    context.set_line_width(line_width)
                    context.set_source_rgb(0, 0, 1)
                    context.stroke()
        
        # render data structure: cols
        for r in range(len(rcols)):
            row = rcols[r]
            for c in range(len(row)):
                cell = row[c]
                for v in cell:
                    x = border + cellwidth*c + border+(cellheight-2*border)/(self.size-1)*(v-1)
                    y1 = border + cellheight*r + border
                    y2 = border + cellheight*r + cellheight - border
                    
                    context.save()
                    context.move_to(x, y1)
                    context.line_to(x, y2)
                    context.set_line_width(line_width)
                    context.set_source_rgb(0, 0, 1)
                    context.stroke()
        
        # render data structure: cells
        for r in range(len(rcells)):
            row = rcells[r]
            for c in range(len(row)):
                cell = row[c]
                for v in cell:
                    x = border + cellwidth*c + border+(cellheight-2*border)/(self.size-1)*(v-1)
                    y = border + cellheight*r + border+(cellheight-2*border)/(self.size-1)*(v-1)
                    i = rrows[r][c].intersection(rcols[r][c].intersection(rcells[r][c]))
                    
                    context.save()
                    context.arc(x, y, radius, 0, 2*pi)
                    context.set_line_width(line_width)
                    
                    if len(i)==1 and list(i)[0]==v:
                        context.set_source_rgb(1, 0, 0)
                    else:
                        context.set_source_rgb(0, 0, 1)
                    context.fill_preserve()
                    context.stroke()

# guard: command line arguments
if len(argv) != 3:
    print('Syntax: %s INPUT_PUZZLE OUTPUT_PDF' % argv[0])
    print('        %s ../var/samples/example1.txt ../var/samples/example1_rule_compliance.pdf' % argv[0])
    exit(1)
input_filename = argv[1]
output_filename = argv[2]

puzzle = RCVisualPuzzle(input_filename)
style = Style()
puzzle.render(output_filename, style)

